yatt:
  cors:
    origins: http://localhost:3000
  jwt:
    issuer:
      uri: http://localhost:8999/realms/eventsourcing-with-axon
    jwks:
      uri: http://localhost:8999/realms/eventsourcing-with-axon/protocol/openid-connect/certs

spring:
  application:
    name: rest-api
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${yatt.jwt.issuer.uri}
          jwk-set-uri: ${yatt.jwt.jwks.uri}

logging:
  level:
    ROOT: warn
    org:
      springframework.boot: info

axon:
  extension:
    tracing:
      enabled: true