# Use the lightweight Nginx image from the previous stage for the nginx container
FROM nginx:stable-alpine
# Copy the build application from the previous stage to the Nginx container
COPY ./dist /usr/share/nginx/html
# Copy the nginx configuration file
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# Expose the port 80
EXPOSE 80
# Start Nginx to serve the application
CMD ["nginx", "-g", "daemon off;"]