yatt:
  cors:
    origins: http://localhost:3000
  jwt:
    issuer:
      uri: http://localhost:8999/realms/eventsourcing-with-axon
    jwks:
      uri: http://localhost:8999/realms/eventsourcing-with-axon/protocol/openid-connect/certs

spring:
  application:
    name: graphql-api
  graphql:
    graphiql:
      enabled: false
    schema:
      printer:
        enabled: true
    websocket:
      path: /wsgraphql
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${yatt.jwt.issuer.uri}
          jwk-set-uri: ${yatt.jwt.jwks.uri}
server:
  port: 8088

logging:
  level:
    ROOT: warn
    io.jaegertracing.internal.reporters.LoggingReporter: info
    org:
      axonframework.eventhandling.pooled.Coordinator: info
      flywaydb.core.internal.command: info
      springframework.boot: info

axon:
  extension:
    tracing:
      enabled: true