spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://localhost:5432/companydb
    username: companyapp
    password: axon
  flyway:
    locations: classpath:db/migration/postgres
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: always
      platform: postgres

logging:
  level:
    ROOT: warn
    org:
      axonframework.eventhandling.pooled.Coordinator: info
      flywaydb.core.internal.command: info
      springframework.boot: info

axon:
  eventhandling:
    processors:
      employee-unique-key-projector:
        mode: subscribing
  extension:
    tracing:
      enabled: true
  serializer:
    events: jackson